name: Manav Garg
markdown: kramdown
theme: jekyll-theme-minimal
baseurl: /

title : manav$ ls
tagline: ...
author :
  name : Manav Garg
  email : manavgarg123@gmail.com
  github : manavgarg
  facebook: manav.garg.982
  twitter : manavgarg92
  linkedin : gargmanav
  stackoverflow : users/5766053
